In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [14]:
df= pd.read_csv("insurance.csv")
print(df.isnull().sum())
print(df['sex'].value_counts())
print(df['smoker'].value_counts())
print(df['region'].value_counts())



x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

print(x[:10])
print(y[:10])

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64
sex
male      676
female    662
Name: count, dtype: int64
smoker
no     1064
yes     274
Name: count, dtype: int64
region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64
[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 [33 'male' 22.705 0 'no' 'northwest']
 [32 'male' 28.88 0 'no' 'northwest']
 [31 'female' 25.74 0 'no' 'southeast']
 [46 'female' 33.44 1 'no' 'southeast']
 [37 'female' 27.74 3 'no' 'northwest']
 [37 'male' 29.83 2 'no' 'northeast']
 [60 'female' 25.84 0 'no' 'northwest']]
[16884.924    1725.5523   4449.462   21984.47061  3866.8552   3756.6216
  8240.5896   7281.5056   6406.4107  28923.13692]


In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columnss=[1,4,5]
ct1= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),columnss)],remainder='passthrough')
x=ct1.fit_transform(x)
print(x[:10])

[[1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 19 27.9 0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 18 33.77 1]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 28 33.0 3]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 33 22.705 0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 32 28.88 0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 31 25.74 0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 46 33.44 1]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 37 27.74 3]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 37 29.83 2]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 60 25.84 0]]


In [16]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest= train_test_split(x,y,test_size=0.2,random_state=0)


print(xtrain[:10])
print(xtest[:10])
print(ytrain[:10])
print(ytest[:10])

[[0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 37 34.1 4]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 18 34.43 0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 23 36.67 2]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 32 35.2 2]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 58 32.395 1]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 25 26.79 2]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 36 35.2 1]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 34 33.25 1]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 53 31.35 0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 45 24.31 5]]
[[0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 52 30.2 1]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 47 29.37 1]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48 40.565 2]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 61 38.38 0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 51 18.05 0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 34 21.375 0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 18 26.315 0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 51 36.385 3]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 38 30.21 3]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 0.0 31 31.065 3]]
[40182.246    1137.4697  38511.6283   4670.64    13019.16105  4189.1131
 387

In [17]:
from sklearn.preprocessing import StandardScaler
st= StandardScaler()
xtrain[:,[-2,-3]]=st.fit_transform(xtrain[:,[-2,-3]])
xtest[:,[-2,-3]]=st.transform(xtest[:,[-2,-3]])

print(xtrain[:10])
print(xtest[:10])

[[0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.0 -0.14853305373631645 0.5453047923915346
  4]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 -1.4978078448262673 0.5986718072290477
  0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 -1.1427355313815433 0.9609206352170169
  2]
 [0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 -0.5036053671810403 0.7231948418499125
  2]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.342770662731524 0.2695752157310497 1]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 -1.0007066060036538 -0.6368554453727748
  2]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 -0.2195475164252612 0.7231948418499125
  1]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 -0.3615764418031508 0.4078442996282427
  1]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 0.9876983492868 0.10057966874559075 0]
 [0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 0.4195826477752418 -1.0379166477880262
  5]]
[[0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.9166838865978553 -0.08539629205180432
  1]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 0.0 0.5616115731531314 -0.21962242027948894
  1]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.6326260358420761 1.5908131285264

In [18]:
st1=StandardScaler()
ytrain=st1.fit_transform(ytrain.reshape(-1,1))
ytest=st1.transform(ytest.reshape(-1,1))

In [19]:
with open('column_transformer.pkl', 'wb') as f:
    pickle.dump(ct1, f)

with open('feature_scaler.pkl', 'wb') as f:
    pickle.dump(st, f)

with open('target_scaler.pkl', 'wb') as f:
    pickle.dump(st1, f)


In [20]:
from sklearn.svm import SVR
regressor= SVR(kernel='rbf')
regressor.fit(xtrain,ytrain)

c:\Users\admin1\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [21]:
y_pred= regressor.predict(xtest)
print(st1.inverse_transform(y_pred.reshape(-1,1)))

[[10855.57956715]
 [ 9430.95205489]
 [46789.96883597]
 [13989.66683018]
 [11042.59429855]
 [ 5186.91490419]
 [ 3308.64915996]
 [12717.30559966]
 [ 8418.27964672]
 [ 5910.28626256]
 [ 8132.04929754]
 [11357.37307155]
 [ 8403.78869911]
 [ 5172.99695573]
 [21856.50400738]
 [12073.00625221]
 [13434.71875119]
 [ 4827.55929328]
 [ 7570.62528844]
 [26377.41554088]
 [23958.15453946]
 [13784.75233554]
 [11311.32760355]
 [27061.28842002]
 [ 2770.83216745]
 [ 5934.598558  ]
 [ 5008.68237577]
 [ 9089.81631287]
 [ 4721.54793505]
 [ 9576.96641124]
 [ 8819.8164637 ]
 [48576.12313258]
 [14117.81894417]
 [11405.8587233 ]
 [13759.78906081]
 [ 5267.50121887]
 [ 9235.96414586]
 [40021.26578381]
 [38641.04701993]
 [ 3056.71119476]
 [ 6754.68976021]
 [ 3654.74119048]
 [23662.47260268]
 [46612.98492924]
 [35367.57822536]
 [ 4864.99978654]
 [12038.60728145]
 [ 8110.59704325]
 [ 5750.40438378]
 [13050.31360026]
 [ 4009.98322428]
 [ 5075.42882776]
 [29443.82392158]
 [43710.89116873]
 [13004.57378238]
 [ 4706.02

In [10]:
from sklearn.metrics import r2_score
print(r2_score(ytest,y_pred))



0.891892398088482


In [11]:
'''case1=[30,'male',29.5,1,'no','northeast']
case1_encoded= ct1.transform([case1])
case1_encoded[:,[-2,-3]]=st.transform(case1_encoded[:,[-2,-3]])
print(case1_encoded[:10])

case_pred= regressor.predict(case1_encoded)
decoded_case= st1.inverse_transform(case_pred.reshape(-1,1))
print(decoded_case)'''

"case1=[30,'male',29.5,1,'no','northeast']\ncase1_encoded= ct1.transform([case1])\ncase1_encoded[:,[-2,-3]]=st.transform(case1_encoded[:,[-2,-3]])\nprint(case1_encoded[:10])\n\ncase_pred= regressor.predict(case1_encoded)\ndecoded_case= st1.inverse_transform(case_pred.reshape(-1,1))\nprint(decoded_case)"

In [12]:
with open('Insurance_prediction_model.pkl','wb') as f:
    pickle.dump(regressor,f)